services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo_app_dev_image
    container_name: todo_app_dev
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - data:/app/data
    ports:
      - 8000:8000
    command: ["./entry/app-entry.sh"]
    networks:
      - todo_network


  redis:
    image: redis:7
    container_name: todo_redis_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
    networks:
      - todo_network

volumes:
  data:

networks:
  todo_network: 
    driver: bridge